version: 1.0.{build}
build_cloud: AUSTIN-TOWER
image: Visual Studio 2019
build_script:
- cmd:mkdir build
- cmd:cd build
- cmd:cmake -G Ninja .. -DCMAKE_C_COMPILER=clang.exe -DCMAKE_CXX_COMPILER=clang.exe
- cmd:ninja
