version: 1.0.{build}
image: Visual Studio 2019
build_script:
- cmd: mkdir build_static_debug
- cmd: cd build_static_debug
- cmd: cmake -G Ninja .. -DCMAKE_C_COMPILER=clang-cl.exe -DCMAKE_CXX_COMPILER=clang-cl.exe -DCMAKE_BUILD_TYPE=Debug -DCI_SYNTHIZER_NAME=synthizerd_static.lib -DSYNTHIZER_LIB_TYPE=STATIC
- cmd: ninja
- cmd: cd ..
- cmd: mkdir build_dynamic_debug
- cmd: cd build_dynamic_debug
- cmd: cmake -G Ninja .. -DCMAKE_C_COMPILER=clang-cl.exe -DCMAKE_CXX_COMPILER=clang-cl.exe -DCMAKE_BUILD_TYPE=Debug -DCI_SYNTHIZER_NAME=synthizerd.lib -DSYNTHIZER_LIB_TYPE=SHARED
- cmd: cd ..
- cmd: mkdir build_static_release
- cmd: cd build_static_release
- cmd: cmake -G Ninja .. -DCMAKE_C_COMPILER=clang-cl.exe -DCMAKE_CXX_COMPILER=clang-cl.exe -DCMAKE_BUILD_TYPE=Release -DCI_SYNTHIZER_NAME=synthizer_static.lib -DSYNTHIZER_LIB_TYPE=STATIC
- cmd: cd ..
- cmd: mkdir build_dynamic_release
- cmd: cd build_dynamic_release
- cmd: cmake -G Ninja .. -DCMAKE_C_COMPILER=clang-cl.exe -DCMAKE_CXX_COMPILER=clang-cl.exe -DCMAKE_BUILD_TYPE=Release -DCI_SYNTHIZER_NAME=synthizer.lib -DSYNTHIZER_LIB_TYPE=SHARED
- cmd: mkdir artifacts
- cmd: copy build_dynamic_debug\synthizerd* artifacts
- cmd: copy build_static_debug\synthizerd_static* artifacts
- cmd: copy build_dynamic_release\synthizer* artifacts
- cmd: copy build_static_release\synthizer_static* artifacts


artifacts:
- path: artifacts
  name: artifacts
  type: zip
  